### ISSUE TITLE
python result  != ncnn result

### ISSUE THREAD

**Issue by wangjing60755** [azeme1/keras2ncnn#16]
I convert h5 model use you code, it sucess. Then I inference ncnn model with c++，I get a segment mask , but the results is no same as python !

**Comment by azeme1** [comment]
Hello, Can you share the model to verify the conversation?12:04, 24 марта 2021 г., wangjing60755 ***@***.***>:
I convert h5 model use you code, it sucess. Then I inference ncnn model with c++，I get a segment mask , but the results is no same as python !

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by wangjing60755** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "azeme1/keras2ncnn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月24日(星期三) 下午5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [azeme1/keras2ncnn] python result  != ncnn result (#16)





 Hello, Can you share the model to verify the conversation?12:04, 24 марта 2021 г., wangjing60755 ***@***.***&gt;:
 I convert h5 model use you code, it sucess. Then I inference ncnn model with c++，I get a segment mask , but the results is no same as python !
 
 —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
 -- Отправлено из мобильного приложения Яндекс.Почты 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

issue_model_20210324.zip (9.84M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=2c653838ffbe5bc99c2c41a41f390b1956060f0b5f0a0d004c540b0c0e140d04070715000c0c5b1b51545e5c090e5a505103080b3921395f12164d5d665456520409670a090b080652570c16435049365c&t=exs_ftn_download&code=ae889996

**Comment by azeme1** [comment]
You can run run_test.py script to get the details of the conversion.
According to it "there are no problems" with the conversion. 

2021-03-24 14:19:22.592131: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-03-24 14:19:22.593634: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-03-24 14:19:27.578640: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-24 14:19:27.583732: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2021-03-24 14:19:28.553176: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-03-24 14:19:28.558917: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: LAPTOP-B8I1GD9G
2021-03-24 14:19:28.559303: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: LAPTOP-B8I1GD9G
2021-03-24 14:19:28.560677: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-03-24 14:19:28.562547: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Nothing to do with Dropout transform

Nothing to do with ReLU transform

Preparation for the transformation...


Weight transfer...
100%|██████████| 123/123 [00:00<00:00, 3083.29it/s]
Checking Transfer :: Random value check
2021-03-24 14:19:30.080005: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
         Transform Error (is less 1e-5) :: 0.0 , True
Activation(relu6): Activation(relu6) is not supported withing NCNN, split by ordinal ReLU and Clip
  0%|          | 0/150 [00:00<?, ?it/s]
Weight transfer...
Checking Transfer :: Random value check
100%|██████████| 150/150 [00:00<00:00, 3497.68it/s]
         Transform Error (is less 1e-5) :: 0.0 , True
SeparableConv2D: It looks like was not implemented in NCNN, splitting it to DepthwiseConv2D and Conv2D 

Weight transfer...
100%|██████████| 154/154 [00:00<00:00, 3151.29it/s]
Checking Transfer :: Random value check
         Transform Error (is less 1e-5) :: 0.0 , True
Conv2D/DepthwiseConv2D->BatchNormalization: Subsequent linear operations can be easily merged for inference

  0%|          | 0/123 [00:00<?, ?it/s]
Weight transfer...
Checking Transfer :: Random value check
100%|██████████| 123/123 [00:00<00:00, 2569.37it/s]
WARNING:tensorflow:5 out of the last 7 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000018F1AC44DC8> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
         Transform Error (is less 1e-5) :: 1.1212660133708141e-08 , True
Nothing to do with BatchNormalization->DepthwiseConv2D transform

Conv2D->ReLU: Inline operations should be merged

Weight transfer...
100%|██████████| 96/96 [00:00<00:00, 3700.65it/s]
Checking Transfer :: Random value check
WARNING:tensorflow:6 out of the last 9 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000018F213EA9D8> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
         Transform Error (is less 1e-5) :: 1.0028304409104294e-08 , True
Nothing to do with Conv2D->Sigmoid transform

Nothing to do with Conv2D->Activation transform

Conv2DSoftmax: Conv2D with Softmax activation can not be transformed. Transforming this to pair Conv2D->Softmax

Weight transfer...
100%|██████████| 97/97 [00:00<00:00, 4228.52it/s]
Checking Transfer :: Random value check
WARNING:tensorflow:7 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000018F1F0E7EE8> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
         Transform Error (is less 1e-5) :: 6.9608998565229285e-09 , True
WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000018F1F689E58> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
100%|██████████| 101/101 [00:00<00:00, 3894.97it/s]

====================Test mode from ./run_test.py====================

====================By Layer Comparison ====================
Layer - input_1 inference MAE :: 1.9845797893935924e-08 < 1e-05 True Keras::(1, 192, 192, 3) / NCNN::(1, 192, 192, 3)
Layer - conv1_pad inference MAE :: 1.9438715526121086e-08 < 1e-05 True Keras::(1, 194, 194, 3) / NCNN::(1, 194, 194, 3)
Layer - conv1 inference MAE :: 3.347918493545876e-07 < 1e-05 True Keras::(1, 96, 96, 16) / NCNN::(1, 96, 96, 16)
Layer - conv1_relu inference MAE :: 2.692661951186892e-07 < 1e-05 True Keras::(1, 96, 96, 16) / NCNN::(1, 96, 96, 16)
Layer - conv_pad_1 inference MAE :: 2.5838787109933037e-07 < 1e-05 True Keras::(1, 98, 98, 16) / NCNN::(1, 98, 98, 16)
Layer - conv_dw_1 inference MAE :: 1.3968873417979921e-06 < 1e-05 True Keras::(1, 96, 96, 16) / NCNN::(1, 96, 96, 16)
Layer - conv_dw_1_relu inference MAE :: 5.08415268996032e-07 < 1e-05 True Keras::(1, 96, 96, 16) / NCNN::(1, 96, 96, 16)
Layer - conv_pw_1 inference MAE :: 8.284841328531911e-07 < 1e-05 True Keras::(1, 96, 96, 32) / NCNN::(1, 96, 96, 32)
Layer - conv_pw_1_relu inference MAE :: 5.694438414138858e-07 < 1e-05 True Keras::(1, 96, 96, 32) / NCNN::(1, 96, 96, 32)
Layer - ncnn_split_1 inference MAE :: 5.694438414138858e-07 < 1e-05 True Keras::(1, 96, 96, 32) / NCNN::(1, 96, 96, 32)
Layer - ncnn_split_1 inference MAE :: 5.694438414138858e-07 < 1e-05 True Keras::(1, 96, 96, 32) / NCNN::(1, 96, 96, 32)
Layer - conv_pad_2 inference MAE :: 5.464385139930528e-07 < 1e-05 True Keras::(1, 98, 98, 32) / NCNN::(1, 98, 98, 32)
Layer - conv_dw_2 inference MAE :: 6.064522040105658e-07 < 1e-05 True Keras::(1, 48, 48, 32) / NCNN::(1, 48, 48, 32)
Layer - conv_dw_2_relu inference MAE :: 5.709713946089323e-07 < 1e-05 True Keras::(1, 48, 48, 32) / NCNN::(1, 48, 48, 32)
Layer - conv_pw_2 inference MAE :: 8.249301686191757e-07 < 1e-05 True Keras::(1, 48, 48, 64) / NCNN::(1, 48, 48, 64)
Layer - conv_pw_2_relu inference MAE :: 7.116321967259864e-07 < 1e-05 True Keras::(1, 48, 48, 64) / NCNN::(1, 48, 48, 64)
Layer - conv_pad_3 inference MAE :: 6.558402674272656e-07 < 1e-05 True Keras::(1, 50, 50, 64) / NCNN::(1, 50, 50, 64)
Layer - conv_dw_3 inference MAE :: 1.4734644082636805e-06 < 1e-05 True Keras::(1, 48, 48, 64) / NCNN::(1, 48, 48, 64)
Layer - conv_dw_3_relu inference MAE :: 1.1727021274055005e-06 < 1e-05 True Keras::(1, 48, 48, 64) / NCNN::(1, 48, 48, 64)
Layer - conv_pw_3 inference MAE :: 1.013529526971979e-06 < 1e-05 True Keras::(1, 48, 48, 64) / NCNN::(1, 48, 48, 64)
Layer - conv_pw_3_relu inference MAE :: 5.551149229177099e-07 < 1e-05 True Keras::(1, 48, 48, 64) / NCNN::(1, 48, 48, 64)
Layer - ncnn_split_2 inference MAE :: 5.551149229177099e-07 < 1e-05 True Keras::(1, 48, 48, 64) / NCNN::(1, 48, 48, 64)
Layer - ncnn_split_2 inference MAE :: 5.551149229177099e-07 < 1e-05 True Keras::(1, 48, 48, 64) / NCNN::(1, 48, 48, 64)
Layer - conv_pad_4 inference MAE :: 5.115939529787283e-07 < 1e-05 True Keras::(1, 50, 50, 64) / NCNN::(1, 50, 50, 64)
Layer - conv_dw_4 inference MAE :: 5.947254066995811e-07 < 1e-05 True Keras::(1, 24, 24, 64) / NCNN::(1, 24, 24, 64)
Layer - conv_dw_4_relu inference MAE :: 5.816998509544646e-07 < 1e-05 True Keras::(1, 24, 24, 64) / NCNN::(1, 24, 24, 64)
Layer - conv_pw_4 inference MAE :: 8.180284680747718e-07 < 1e-05 True Keras::(1, 24, 24, 128) / NCNN::(1, 24, 24, 128)
Layer - conv_pw_4_relu inference MAE :: 8.170907221938251e-07 < 1e-05 True Keras::(1, 24, 24, 128) / NCNN::(1, 24, 24, 128)
Layer - conv_pad_5 inference MAE :: 6.962192173887161e-07 < 1e-05 True Keras::(1, 26, 26, 128) / NCNN::(1, 26, 26, 128)
Layer - conv_dw_5 inference MAE :: 7.274404651980149e-07 < 1e-05 True Keras::(1, 24, 24, 128) / NCNN::(1, 24, 24, 128)
Layer - conv_dw_5_relu inference MAE :: 7.2451069854651e-07 < 1e-05 True Keras::(1, 24, 24, 128) / NCNN::(1, 24, 24, 128)
Layer - conv_pw_5 inference MAE :: 5.82340874188958e-07 < 1e-05 True Keras::(1, 24, 24, 128) / NCNN::(1, 24, 24, 128)
Layer - conv_pw_5_relu inference MAE :: 5.317002091942413e-07 < 1e-05 True Keras::(1, 24, 24, 128) / NCNN::(1, 24, 24, 128)
Layer - ncnn_split_3 inference MAE :: 5.317002091942413e-07 < 1e-05 True Keras::(1, 24, 24, 128) / NCNN::(1, 24, 24, 128)
Layer - ncnn_split_3 inference MAE :: 5.317002091942413e-07 < 1e-05 True Keras::(1, 24, 24, 128) / NCNN::(1, 24, 24, 128)
Layer - conv_pad_6 inference MAE :: 4.53046283155345e-07 < 1e-05 True Keras::(1, 26, 26, 128) / NCNN::(1, 26, 26, 128)
Layer - conv_dw_6 inference MAE :: 4.545545948531071e-07 < 1e-05 True Keras::(1, 12, 12, 128) / NCNN::(1, 12, 12, 128)
Layer - conv_dw_6_relu inference MAE :: 4.544769751646527e-07 < 1e-05 True Keras::(1, 12, 12, 128) / NCNN::(1, 12, 12, 128)
Layer - conv_pw_6 inference MAE :: 7.701557933614822e-07 < 1e-05 True Keras::(1, 12, 12, 256) / NCNN::(1, 12, 12, 256)
Layer - conv_pw_6_relu inference MAE :: 7.698841955061653e-07 < 1e-05 True Keras::(1, 12, 12, 256) / NCNN::(1, 12, 12, 256)
Layer - conv_pad_7 inference MAE :: 5.656292501043936e-07 < 1e-05 True Keras::(1, 14, 14, 256) / NCNN::(1, 14, 14, 256)
Layer - conv_dw_7 inference MAE :: 6.006336548125546e-07 < 1e-05 True Keras::(1, 12, 12, 256) / NCNN::(1, 12, 12, 256)
Layer - conv_dw_7_relu inference MAE :: 5.99935162881593e-07 < 1e-05 True Keras::(1, 12, 12, 256) / NCNN::(1, 12, 12, 256)
Layer - conv_pw_7 inference MAE :: 7.284047569555696e-07 < 1e-05 True Keras::(1, 12, 12, 256) / NCNN::(1, 12, 12, 256)
Layer - conv_pw_7_relu inference MAE :: 7.260894108185312e-07 < 1e-05 True Keras::(1, 12, 12, 256) / NCNN::(1, 12, 12, 256)
Layer - conv_pad_8 inference MAE :: 5.334533739187464e-07 < 1e-05 True Keras::(1, 14, 14, 256) / NCNN::(1, 14, 14, 256)
Layer - conv_dw_8 inference MAE :: 4.7349556098197354e-07 < 1e-05 True Keras::(1, 12, 12, 256) / NCNN::(1, 12, 12, 256)
Layer - conv_dw_8_relu inference MAE :: 4.721115374195506e-07 < 1e-05 True Keras::(1, 12, 12, 256) / NCNN::(1, 12, 12, 256)
Layer - conv_pw_8 inference MAE :: 7.72353359934641e-07 < 1e-05 True Keras::(1, 12, 12, 256) / NCNN::(1, 12, 12, 256)
Layer - conv_pw_8_relu inference MAE :: 7.72353359934641e-07 < 1e-05 True Keras::(1, 12, 12, 256) / NCNN::(1, 12, 12, 256)
Layer - conv_pad_9 inference MAE :: 5.674432372870797e-07 < 1e-05 True Keras::(1, 14, 14, 256) / NCNN::(1, 14, 14, 256)
Layer - conv_dw_9 inference MAE :: 5.552839184019831e-07 < 1e-05 True Keras::(1, 12, 12, 256) / NCNN::(1, 12, 12, 256)
Layer - conv_dw_9_relu inference MAE :: 5.547794330595934e-07 < 1e-05 True Keras::(1, 12, 12, 256) / NCNN::(1, 12, 12, 256)
Layer - conv_pw_9 inference MAE :: 9.33760816224094e-07 < 1e-05 True Keras::(1, 12, 12, 256) / NCNN::(1, 12, 12, 256)
Layer - conv_pw_9_relu inference MAE :: 9.333857065030315e-07 < 1e-05 True Keras::(1, 12, 12, 256) / NCNN::(1, 12, 12, 256)
Layer - conv_pad_10 inference MAE :: 6.857527523607132e-07 < 1e-05 True Keras::(1, 14, 14, 256) / NCNN::(1, 14, 14, 256)
Layer - conv_dw_10 inference MAE :: 5.648965384352778e-07 < 1e-05 True Keras::(1, 12, 12, 256) / NCNN::(1, 12, 12, 256)
Layer - conv_dw_10_relu inference MAE :: 5.622189860332583e-07 < 1e-05 True Keras::(1, 12, 12, 256) / NCNN::(1, 12, 12, 256)
Layer - conv_pw_10 inference MAE :: 8.628213663541828e-07 < 1e-05 True Keras::(1, 12, 12, 256) / NCNN::(1, 12, 12, 256)
Layer - conv_pw_10_relu inference MAE :: 8.386069794141804e-07 < 1e-05 True Keras::(1, 12, 12, 256) / NCNN::(1, 12, 12, 256)
Layer - conv_pad_11 inference MAE :: 6.161193937259668e-07 < 1e-05 True Keras::(1, 14, 14, 256) / NCNN::(1, 14, 14, 256)
Layer - conv_dw_11 inference MAE :: 6.129306484581321e-07 < 1e-05 True Keras::(1, 12, 12, 256) / NCNN::(1, 12, 12, 256)
Layer - conv_dw_11_relu inference MAE :: 6.090889428378432e-07 < 1e-05 True Keras::(1, 12, 12, 256) / NCNN::(1, 12, 12, 256)
Layer - conv_pw_11 inference MAE :: 1.282932657886704e-06 < 1e-05 True Keras::(1, 12, 12, 256) / NCNN::(1, 12, 12, 256)
Layer - conv_pw_11_relu inference MAE :: 1.2601152548086247e-06 < 1e-05 True Keras::(1, 12, 12, 256) / NCNN::(1, 12, 12, 256)
Layer - ncnn_split_4 inference MAE :: 1.2601152548086247e-06 < 1e-05 True Keras::(1, 12, 12, 256) / NCNN::(1, 12, 12, 256)
Layer - ncnn_split_4 inference MAE :: 1.2601152548086247e-06 < 1e-05 True Keras::(1, 12, 12, 256) / NCNN::(1, 12, 12, 256)
Layer - conv_pad_12 inference MAE :: 9.257988722310984e-07 < 1e-05 True Keras::(1, 14, 14, 256) / NCNN::(1, 14, 14, 256)
Layer - conv_dw_12 inference MAE :: 7.422318617500423e-07 < 1e-05 True Keras::(1, 6, 6, 256) / NCNN::(1, 6, 6, 256)
Layer - conv_dw_12_relu inference MAE :: 7.208114425338863e-07 < 1e-05 True Keras::(1, 6, 6, 256) / NCNN::(1, 6, 6, 256)
Layer - conv_pw_12 inference MAE :: 1.1411802915972658e-06 < 1e-05 True Keras::(1, 6, 6, 512) / NCNN::(1, 6, 6, 512)
Layer - conv_pw_12_relu inference MAE :: 1.1189837323399843e-06 < 1e-05 True Keras::(1, 6, 6, 512) / NCNN::(1, 6, 6, 512)
Layer - conv_pad_13 inference MAE :: 6.294283707575232e-07 < 1e-05 True Keras::(1, 8, 8, 512) / NCNN::(1, 8, 8, 512)
Layer - conv_dw_13 inference MAE :: 9.954105735232588e-07 < 1e-05 True Keras::(1, 6, 6, 512) / NCNN::(1, 6, 6, 512)
Layer - conv_dw_13_relu inference MAE :: 9.64676928560948e-07 < 1e-05 True Keras::(1, 6, 6, 512) / NCNN::(1, 6, 6, 512)
Layer - conv_pw_13 inference MAE :: 1.9068245364906034e-06 < 1e-05 True Keras::(1, 6, 6, 512) / NCNN::(1, 6, 6, 512)
Layer - conv_pw_13_relu inference MAE :: 1.5772398000990506e-06 < 1e-05 True Keras::(1, 6, 6, 512) / NCNN::(1, 6, 6, 512)
Layer - conv_pw_mobile_bottleneck inference MAE :: 2.1476123947650194e-05 < 1e-05 False Keras::(1, 6, 6, 32) / NCNN::(1, 6, 6, 32)
Layer - conv_pw_upblock_4 inference MAE :: 1.4418247701541986e-05 < 1e-05 False Keras::(1, 12, 12, 32) / NCNN::(1, 12, 12, 32)
Layer - up_sampling2d inference MAE :: 2.1476123947650194e-05 < 1e-05 False Keras::(1, 12, 12, 32) / NCNN::(1, 12, 12, 32)
Layer - add inference MAE :: 2.7383435735828243e-05 < 1e-05 False Keras::(1, 12, 12, 32) / NCNN::(1, 12, 12, 32)
Layer - sep_upblock_4b_dwc_127 inference MAE :: 2.485200275259558e-05 < 1e-05 False Keras::(1, 12, 12, 32) / NCNN::(1, 12, 12, 32)
Layer - sep_upblock_4b inference MAE :: 3.6985406950407196e-06 < 1e-05 True Keras::(1, 12, 12, 32) / NCNN::(1, 12, 12, 32)
Layer - leaky_re_lu inference MAE :: 3.120315795968054e-06 < 1e-05 True Keras::(1, 12, 12, 32) / NCNN::(1, 12, 12, 32)
Layer - conv_pw_upblock_3 inference MAE :: 1.7404266827725223e-06 < 1e-05 True Keras::(1, 24, 24, 32) / NCNN::(1, 24, 24, 32)
Layer - up_sampling2d_1 inference MAE :: 3.120315795968054e-06 < 1e-05 True Keras::(1, 24, 24, 32) / NCNN::(1, 24, 24, 32)
Layer - add_1 inference MAE :: 3.7169043025642168e-06 < 1e-05 True Keras::(1, 24, 24, 32) / NCNN::(1, 24, 24, 32)
Layer - sep_upblock_3b_dwc_134 inference MAE :: 4.041599822812714e-06 < 1e-05 True Keras::(1, 24, 24, 32) / NCNN::(1, 24, 24, 32)
Layer - sep_upblock_3b inference MAE :: 3.0996570785646327e-06 < 1e-05 True Keras::(1, 24, 24, 32) / NCNN::(1, 24, 24, 32)
Layer - leaky_re_lu_1 inference MAE :: 2.1057442154415185e-06 < 1e-05 True Keras::(1, 24, 24, 32) / NCNN::(1, 24, 24, 32)
Layer - conv_pw_upblock_2 inference MAE :: 1.5457434301424655e-06 < 1e-05 True Keras::(1, 48, 48, 32) / NCNN::(1, 48, 48, 32)
Layer - up_sampling2d_2 inference MAE :: 2.105743988067843e-06 < 1e-05 True Keras::(1, 48, 48, 32) / NCNN::(1, 48, 48, 32)
Layer - add_2 inference MAE :: 2.7404898901295383e-06 < 1e-05 True Keras::(1, 48, 48, 32) / NCNN::(1, 48, 48, 32)
Layer - sep_upblock_2b_dwc_141 inference MAE :: 3.148664745822316e-06 < 1e-05 True Keras::(1, 48, 48, 32) / NCNN::(1, 48, 48, 32)
Layer - sep_upblock_2b inference MAE :: 2.5208091756212525e-06 < 1e-05 True Keras::(1, 48, 48, 32) / NCNN::(1, 48, 48, 32)
Layer - leaky_re_lu_2 inference MAE :: 1.7989400475926232e-06 < 1e-05 True Keras::(1, 48, 48, 32) / NCNN::(1, 48, 48, 32)
Layer - conv_pw_upblock_1 inference MAE :: 1.0494823072804138e-06 < 1e-05 True Keras::(1, 96, 96, 32) / NCNN::(1, 96, 96, 32)
Layer - up_sampling2d_3 inference MAE :: 1.7989400475926232e-06 < 1e-05 True Keras::(1, 96, 96, 32) / NCNN::(1, 96, 96, 32)
Layer - add_3 inference MAE :: 2.2283156795310788e-06 < 1e-05 True Keras::(1, 96, 96, 32) / NCNN::(1, 96, 96, 32)
Layer - sep_upblock_1b_dwc_148 inference MAE :: 2.640631009853678e-06 < 1e-05 True Keras::(1, 96, 96, 32) / NCNN::(1, 96, 96, 32)
Layer - sep_upblock_1b inference MAE :: 1.6395964621551684e-06 < 1e-05 True Keras::(1, 96, 96, 32) / NCNN::(1, 96, 96, 32)
Layer - leaky_re_lu_3 inference MAE :: 1.0777129091366078e-06 < 1e-05 True Keras::(1, 96, 96, 32) / NCNN::(1, 96, 96, 32)
Layer - up_sampling2d_4 inference MAE :: 1.0777125680760946e-06 < 1e-05 True Keras::(1, 192, 192, 32) / NCNN::(1, 192, 192, 32)
Layer - final_layer_act_95 inference MAE :: 5.336869435268454e-06 < 1e-05 True Keras::(1, 192, 192, 2) / NCNN::(1, 192, 192, 2)
Layer - final_layer inference MAE :: 1.6579814854367214e-08 < 1e-05 True Keras::(1, 192, 192, 2) / NCNN::(1, 192, 192, 2)
Estimated float32 inference memory :: 38 MB
./unit_test_output/model

Process finished with exit code 0

**Comment by azeme1** [comment]
**According to   evaluate_nail.py**   
 image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
 image = np.array(image / 255., dtype=np.float32)
 input_image = cv2.resize(image, INPUT_SHAPE)

**but according to the ncnn_inference.cpp**
	ncnn::Mat in_ = ncnn::Mat::from_pixels_resize(bgr.data, ncnn::Mat::PIXEL_RGB, bgr.cols, bgr.rows, INPUT_SIZE, INPUT_SIZE);

The correct way I think is to call 
	ncnn::Mat in_ = ncnn::Mat::from_pixels_resize(bgr.data, ncnn::Mat::PIXEL_RGB2BGR, bgr.cols, bgr.rows, INPUT_SIZE, INPUT_SIZE);

**Comment by wangjing60755** [comment]
I tryed, but no use.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "azeme1/keras2ncnn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月24日(星期三) 晚上7:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [azeme1/keras2ncnn] python result  != ncnn result (#16)





 
According to   evaluate_nail.py
 image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
 image = np.array(image / 255., dtype=np.float32)
 input_image = cv2.resize(image, INPUT_SHAPE)
 
but according to the ncnn_inference.cpp
 ncnn::Mat in_ = ncnn::Mat::from_pixels_resize(bgr.data, ncnn::Mat::PIXEL_RGB, bgr.cols, bgr.rows, INPUT_SIZE, INPUT_SIZE);
 
The correct way I think is to call
 ncnn::Mat in_ = ncnn::Mat::from_pixels_resize(bgr.data, ncnn::Mat::PIXEL_RGB2BGR, bgr.cols, bgr.rows, INPUT_SIZE, INPUT_SIZE);

**Comment by azeme1** [comment]
There is the issue in you CPP file than is my result from you model
(There is probably issues with NCNN inference, but according to my experience the issue in CPP) 
The result from CPU version is below
![demo](https://user-images.githubusercontent.com/7568330/112306879-5f3f0e00-8cb1-11eb-92a9-65634c882fda.png)

**Comment by wangjing60755** [comment]
can you give me you inference coding with ncnn? I can,t find&nbsp;problem




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "azeme1/keras2ncnn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月24日(星期三) 晚上8:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [azeme1/keras2ncnn] python result  != ncnn result (#16)





 
There is the issue in you CPP file than is my result from you model
 (There is probably issues with NCNN inference, but according to my experience the issue in CPP)
 The result from CPU version is below

**Comment by azeme1** [comment]
[DropBox](https://www.dropbox.com/sh/8anok3k3jxjj81i/AADWMLad_V0MKs4ySN2mgPPda?dl=0)
keras2ncnn >model_zoo > variouse > issue_00016 > demo.py

**Comment by azeme1** [comment]
Try to disable vulkan as well - sometimes this can be an issue...

**Comment by wangjing60755** [comment]
How can you use ncnn in python with import?&nbsp;Have you tried in CPP？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "azeme1/keras2ncnn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月24日(星期三) 晚上8:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [azeme1/keras2ncnn] python result  != ncnn result (#16)





 
Try to disable vulkan as well - sometimes this can be an issue...

**Comment by azeme1** [comment]
I also suggest you to rework your model if you care about the model inference time
1) Include padding in to the convolution
2) Try to exclude ReLU6 - try to use mergeable by NCNN activations 
3) As soon you are using binary segmentation - replace softmax with sigmoid

**Comment by azeme1** [comment]
>> How can you use ncnn in python with import?&nbsp;Have you tried in CPP？

The result should be same because pyncnn is a simple wrapper over C++. 
I have check the this with other networks 
Here is the example with the plugin
https://www.youtube.com/watch?v=n_1ZSGy9zkA
of this model
https://github.com/azeme1/keras2ncnn/tree/main/model_zoo/segmentation/hair/model_000

**Comment by azeme1** [comment]
https://github.com/Tencent/ncnn/tree/master/python

**Comment by azeme1** [comment]
Do you succeed to fix the issue?

**Comment by wangjing60755** [comment]
yes，thanks

---Original---
From: ***@***.***&gt;
Date: Thu, Mar 25, 2021 21:21 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [azeme1/keras2ncnn] python result  != ncnn result (#16)




 
Do you succeed to fix the issue?
